### ISSUE TITLE
Problems with the Karrer algorithm

### ISSUE THREAD

**Issue by aaleta** [netsiphd/netrw#13]
I believe that there are a couple of issues with the algorithm:

- It is unclear if the method is for directed or undirected networks. For instance, imagine that the network is undirected and the link (0,1) exists. The set potential_edges will contain the edge (1,0). Then, one may destroy (0,1) and create (1,0), wasting one rewiring. Or one may destroy (0,2) and add (1,0) when (0,1) already exists. If the method is meant for undirected networks one way to fix this would be to use permutations rather than itertools product.

- The method should "go through each edge in the original network in turn and with probability alpha we remove it and replace it". The current implementation only checks one link. If the function is called |E| number of times, it is not guaranteed that each time a different edge will be checked.

**Comment by sdmccabe** [comment]
Yeah, I regret hitting merge on what was mostly an example. It needs a few fixes throughout.

**Comment by aaleta** [comment]
I can work on it if you want
